import enum


class UserRole(str, enum.Enum):
    PROVIDER = "PROVIDER"
    INFUSION_ADMIN = "INFUSION_ADMIN"


class OrgType(str, enum.Enum):
    PROVIDER_ORG = "PROVIDER_ORG"
    INFUSION_ORG = "INFUSION_ORG"


class CaseStatus(str, enum.Enum):
    REFERRAL_RECEIVED = "REFERRAL_RECEIVED"
    CLINICAL_COMPLETENESS_CHECK = "CLINICAL_COMPLETENESS_CHECK"
    BENEFITS_INVESTIGATION = "BENEFITS_INVESTIGATION"
    PRIOR_AUTH_SUBMITTED = "PRIOR_AUTH_SUBMITTED"
    PRIOR_AUTH_APPROVED = "PRIOR_AUTH_APPROVED"
    FINANCIAL_COUNSELING_PENDING = "FINANCIAL_COUNSELING_PENDING"
    FINANCIAL_CLEARED = "FINANCIAL_CLEARED"
    WELCOME_CALL_PENDING = "WELCOME_CALL_PENDING"
    WELCOME_CALL_COMPLETED = "WELCOME_CALL_COMPLETED"
    SCHEDULING_READY = "SCHEDULING_READY"
    SCHEDULED = "SCHEDULED"
    PHARMACY_PUSH_PENDING = "PHARMACY_PUSH_PENDING"
    PHARMACY_PUSHED = "PHARMACY_PUSHED"
    DRUG_FULFILLMENT_IN_PROGRESS = "DRUG_FULFILLMENT_IN_PROGRESS"
    DRUG_READY = "DRUG_READY"
    INFUSION_COMPLETED = "INFUSION_COMPLETED"
    ON_THERAPY = "ON_THERAPY"
    DISCONTINUED = "DISCONTINUED"


class TaskType(str, enum.Enum):
    CLINICAL_REVIEW = "CLINICAL_REVIEW"
    BENEFITS_INVESTIGATION = "BENEFITS_INVESTIGATION"
    PRIOR_AUTH = "PRIOR_AUTH"
    FINANCIAL_COUNSELING = "FINANCIAL_COUNSELING"
    WELCOME_CALL = "WELCOME_CALL"
    SCHEDULING = "SCHEDULING"
    PHARMACY_PUSH = "PHARMACY_PUSH"
    DOCUMENT_REQUEST = "DOCUMENT_REQUEST"
    GENERAL = "GENERAL"


class TaskStatus(str, enum.Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    CANCELLED = "CANCELLED"


class FulfillmentStatus(str, enum.Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    READY = "READY"
    SHIPPED = "SHIPPED"
    RECEIVED = "RECEIVED"


class WelcomeCallOutcome(str, enum.Enum):
    REACHED = "REACHED"
    VOICEMAIL = "VOICEMAIL"
    NO_ANSWER = "NO_ANSWER"
    NEEDS_CALL_BACK = "NEEDS_CALL_BACK"
